version: '3.8'

services:
  app:
    container_name: qr-url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - qr-network
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: qr-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - qr-network
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: qr-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qr_db
      MYSQL_USER: qr_user
      MYSQL_PASSWORD: qr_password
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - qr-network

networks:
  qr-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local